-- Evolução aditiva: nenhum dado financeiro é apagado.
CREATE TYPE "PaymentMethod" AS ENUM ('PIX','DEBITO','CREDITO','DINHEIRO','BOLETO','TRANSFERENCIA','OUTRO');
ALTER TYPE "TransactionStatus" ADD VALUE 'CANCELADA';
ALTER TABLE "Household" ADD COLUMN "mode" TEXT NOT NULL DEFAULT 'REAL';
UPDATE "Household" SET "mode" = 'DEMO' WHERE "id" = 'household-demo';
ALTER TABLE "Account" ADD COLUMN "openingDate" DATE NOT NULL DEFAULT '1970-01-01', ADD COLUMN "color" TEXT NOT NULL DEFAULT '#4389ff', ADD COLUMN "notes" TEXT NOT NULL DEFAULT '';
ALTER TABLE "CreditCard" ADD COLUMN "paymentAccountId" TEXT;
ALTER TABLE "CreditCard" ADD CONSTRAINT "CreditCard_paymentAccountId_fkey" FOREIGN KEY ("paymentAccountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Transaction" ADD COLUMN "paymentMethod" "PaymentMethod" NOT NULL DEFAULT 'OUTRO', ADD COLUMN "dueDate" DATE, ADD COLUMN "cancelledAt" TIMESTAMP(3);
UPDATE "Transaction" SET "paymentMethod" = 'CREDITO' WHERE "cardId" IS NOT NULL;
UPDATE "Transaction" SET "paymentMethod" = 'TRANSFERENCIA' WHERE "type" = 'TRANSFERENCIA';
UPDATE "Transaction" SET "dueDate" = "date"::date WHERE "status" = 'PENDENTE';
ALTER TABLE "Attachment" ADD COLUMN "fileSize" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "source" "TransactionSource" NOT NULL DEFAULT 'MANUAL', ADD COLUMN "householdId" TEXT;
UPDATE "Attachment" a SET "householdId"=t."householdId" FROM "Transaction" t WHERE a."transactionId"=t.id;
UPDATE "Attachment" a SET "householdId"=e."householdId" FROM "ExternalImport" e WHERE a."externalImportId"=e.id AND a."householdId" IS NULL;
CREATE TABLE "InvoicePayment" ("id" TEXT NOT NULL,"invoiceId" TEXT NOT NULL,"transactionId" TEXT NOT NULL,CONSTRAINT "InvoicePayment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "InvoicePayment_transactionId_key" ON "InvoicePayment"("transactionId");
CREATE INDEX "InvoicePayment_invoiceId_idx" ON "InvoicePayment"("invoiceId");
ALTER TABLE "InvoicePayment" ADD CONSTRAINT "InvoicePayment_invoiceId_fkey" FOREIGN KEY ("invoiceId") REFERENCES "Invoice"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "InvoicePayment" ADD CONSTRAINT "InvoicePayment_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
INSERT INTO "InvoicePayment"("id","invoiceId","transactionId") SELECT 'payment-'||id,"paymentInvoiceId",id FROM "Transaction" WHERE "paymentInvoiceId" IS NOT NULL;
CREATE TABLE "Installment" ("id" TEXT NOT NULL,"purchaseId" TEXT NOT NULL,"transactionId" TEXT NOT NULL,"number" INTEGER NOT NULL,CONSTRAINT "Installment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Installment_transactionId_key" ON "Installment"("transactionId");
CREATE UNIQUE INDEX "Installment_purchaseId_number_key" ON "Installment"("purchaseId","number");
ALTER TABLE "Installment" ADD CONSTRAINT "Installment_purchaseId_fkey" FOREIGN KEY ("purchaseId") REFERENCES "InstallmentPurchase"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Installment" ADD CONSTRAINT "Installment_transactionId_fkey" FOREIGN KEY ("transactionId") REFERENCES "Transaction"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
INSERT INTO "Installment"("id","purchaseId","transactionId","number") SELECT 'part-'||id,"installmentPurchaseId",id,"installmentNumber" FROM "Transaction" WHERE "installmentPurchaseId" IS NOT NULL AND "installmentNumber" IS NOT NULL;
CREATE INDEX "Transaction_householdId_status_date_idx" ON "Transaction"("householdId","status","date");
CREATE INDEX "Transaction_accountId_date_idx" ON "Transaction"("accountId","date");
CREATE INDEX "Transaction_destinationAccountId_date_idx" ON "Transaction"("destinationAccountId","date");
CREATE INDEX "Transaction_cardId_date_idx" ON "Transaction"("cardId","date");
CREATE INDEX "Transaction_categoryId_idx" ON "Transaction"("categoryId");
CREATE INDEX "Transaction_invoiceId_idx" ON "Transaction"("invoiceId");
CREATE INDEX "Transaction_paymentInvoiceId_idx" ON "Transaction"("paymentInvoiceId");
