export const banks = [
  ["nubank", "Nubank"],
  ["itau", "Itaú"],
  ["bradesco", "Bradesco"],
  ["bb", "Banco do Brasil"],
  ["caixa", "Caixa"],
  ["santander", "Santander"],
  ["inter", "Inter"],
  ["c6", "C6 Bank"],
  ["picpay", "PicPay"],
  ["mercadopago", "Mercado Pago"],
  ["pagbank", "PagBank"],
  ["btg", "BTG Pactual"],
  ["xp", "XP"],
  ["sicoob", "Sicoob"],
  ["sicredi", "Sicredi"],
  ["outro", "Outro"],
].map(([id, name]) => ({ id, name }));
export const categories = [
  ["Moradia", "home", "#8a91fa"],
  ["Mercado", "food", "#f5675d"],
  ["Alimentação", "food", "#f5675d"],
  ["Restaurantes", "food", "#ec8e53"],
  ["Transporte", "car", "#3ec7b4"],
  ["Combustível", "car", "#3aa8cf"],
  ["Saúde", "wallet", "#ea708c"],
  ["Farmácia", "wallet", "#f084b4"],
  ["Educação", "receipt", "#77a1e9"],
  ["Assinaturas", "receipt", "#65a4f5"],
  ["Lazer", "music", "#d276e6"],
  ["Viagens", "car", "#62bcbd"],
  ["Compras", "wallet", "#ffb547"],
  ["Pets", "home", "#b59876"],
  ["Presentes", "wallet", "#dd8aaf"],
  ["Impostos", "receipt", "#b283bc"],
  ["Salário", "wallet", "#51c796"],
  ["Freelance", "wallet", "#30b89b"],
  ["Rendimentos", "wallet", "#65ad82"],
  ["Outros", "wallet", "#ffb547"],
].map(([name, icon, color]) => ({ name, icon, color }));
